Implemented heatmap based on Smash Magazine landing page.
pointerish/Design-Teardown-Microverse pull request #1
Opened 2020-09-30 20:32 UTC by pointerish

The heatmap is in the scale of grey. This was done for the Microverse UI/UX module.

2020-10-01 22:40 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Good job on your project. However, there a few changes required.**

1). **Please use `<article>` tags for all your articles.**

2). **Ensure that articles on the same row share an equal portion of the page total width. For example, in the screenshot below, you gave each article a width of 40% instead of 50%. Please adjust that.**

![design_clone](https://user-images.githubusercontent.com/38922385/94868241-79f3a100-044b-11eb-9a2b-0a646788564d.png)

3). **Images used on your page should also be grayscale(white, black or any shade of grey). Hint: Image filters can help you with this.**

4). **Change all the blue links to grayscale colors.**

5). **Convert your footer list to links. It is a requirement that the footer should have centered links.**

6). **Add a Getting started section, on your readme file, with instructions on how one can set up your project locally and the necessary tools required. You can use this readme [template](https://github.com/microverseinc/readme-template) as reference.**

7). **Remove the page horizontal scroll.**

### Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi)**

2020-10-02 01:08 UTC, pointerish commented
Hi!

See the screenshot below:

![expected50](https://user-images.githubusercontent.com/25916517/94877902-12bcf900-0419-11eb-8581-797c8efac6f5.png)

This is with the articles taking 50% of the width as requested by the previous TSE. Personally this seems to attempt against aesthetics but if that is expected then that's okay.

We previously had 40% and the articles looked like floating blocks with a ligther background. We preferred that, but we understand these projects are not based upon our personal preferences.

Thank you for all your help!

2020-10-02 02:23 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Hi, @pointerish and @imran5644,

Both of you have done well on this project.

Hello team, don't forget the goal for this project is to start training yourself to think in terms of visual hierarchy, typography, and design principles. Meaning the weight of each section in terms of colors, which catches your attention first.

If you get this, you will understand what the previous TSE meant, here is a [chrome extension](https://chrome.google.com/webstore/detail/grayscale-the-web-save-si/mblmpdpfppogibmoobibfannckeeleag?hl=en) that will make your job simple, more emphasis is how you represent these visual hierarchies.

Note: Again! emphasis is on the visual hierarchy! See the color variation on the screenshot below:
<img width="1438" alt="Screen Shot 2020-10-02 at 3 19 23 AM" src="https://user-images.githubusercontent.com/5264771/94881851-5f76f300-045e-11eb-9a29-659832b56da1.png">

Make these changes to your design and you should be good to go.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-02 18:01 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Great job so far, team! 👏 
You did well implementing the changes required by the previous TSE 👍 
You are almost there! 😃 

Just a few adjustments and ready to go! ⏩ 
Kindly, check my comments below 👇  apply the changes and resubmit your project for a new code review

Good luck!

## Changes
- Kindly add more links to your footer, we are trying to make clear the hierarchy and importance of each element in the website. Check the difference between the original and your project 👇 
![Capture1](https://user-images.githubusercontent.com/56809963/94954418-672fa980-04e9-11eb-854c-4a4eb4660ceb.PNG)
![Capture](https://user-images.githubusercontent.com/56809963/94954424-6860d680-04e9-11eb-9677-aa5fc7819f89.PNG)
- In the community links section, the layout is not the same as the original website, which makes that the importance of every elements is different. Kindly, modify the layout and apply the corresponding colour.
![Capture3](https://user-images.githubusercontent.com/56809963/94954607-a4943700-04e9-11eb-8aeb-1b12e9b9f975.PNG)
![Capture2](https://user-images.githubusercontent.com/56809963/94954615-a5c56400-04e9-11eb-84c7-1f82c261318e.PNG)
- Kindly add the 'seriously, ted?' banner in the main section. It modifies the hierarchy
![Capture4](https://user-images.githubusercontent.com/56809963/94954721-cf7e8b00-04e9-11eb-861c-cddf8945e815.PNG)
 of the site

2020-10-02 18:01 UTC, javitocor commented on README.md
> +
Make each technology in a different line

2020-10-02 18:01 UTC, javitocor commented on README.md
> +
This section should before the author's section so the users do not need to scroll down

2020-10-02 20:56 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team,

**Your project is good but there is still a horizontal scroll on your page. Please fix that and send for another review.**

### Happy coding 😃.

**ps: You can reach me on slack(Rose Wanjohi).**

2020-10-02 21:19 UTC, pointerish commented
Hi TSEs,

We have updated the screenshot and we have also removed the unneeded horizontal scrolling. Thanks for the patience and for the feedback!

2020-10-02 21:23 UTC, blackpintz approved these changes
# Status: Approved.

**Congratulations team and all the best in your next project 😃.**

2020-10-02 21:23 UTC, merged